eureka:
  instance:
      statusPageUrlPath: /actuator/info
      healthCheckUrlPath: /actuator/health
      prefer-ip-address: true
      ip-address: 127.0.0.1
  client:
      serviceUrl:
          defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9000}/eureka/
server:
  port: 8700
spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: demo-base
        uri: lb://demo-base
        predicates:
        - Path=/base/**
        filters:
        - StripPrefix=1
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

    