eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 8700
spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  #zipkin:
    #base-url: http://localhost:5001
zuul:
  routes:
    trade-service:
      path: /hotel-trade/**
      serviceId: hotel-trade-service-nw
    hotel-service:
      path: /hotel-service/**
      serviceId: hotel-search-service-nw
    base-service:
      path: /hotel-base/**
      serviceId: hotel-base-nw
    air-service:
      path: /flight/**
      serviceId: air-ticker-service-nw
    