eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 8899

zuul:  
  host:  
    socket-timeout-millis: 60000  
    connect-timeout-millis: 60000  
  
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 60000  
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000 