eureka:
  instance:
      statusPageUrlPath: /actuator/info
      healthCheckUrlPath: /actuator/health
      prefer-ip-address: true
      ip-address: 127.0.0.1
  client:
      serviceUrl:
          defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9000}/eureka/
server:
  port: 8866
spring:
  main:
    web-application-type: reactive
    